const PathConstants = {
  Home: "/",
  Login: "/login",
  Test: "/test",
  Call: {
    Consultation: "/call/consultation",
    SearchCustomer: "/call/consultation/customer-search",
    ConsultationStatus: "/call/consultation/consultation-status",
    CallLog: "/call/consultation/call-log",
    SmsSending: "/call/consultation/sms-sending",
    Analysis: "/call/analysis",
    UploadConsultation: "/call/analysis/upload-consultation",
    CreateConsultation: "/call/analysis/create-consultation",
    TopicRegistration: "/call/analysis/topic-registration",
    Management: "/call/management",
    Information: "/call/information",
  },
  Message: {
    Auto: "/message/auto",
    Bulk: "/message/bulk",
    Declaration: "/message/declaration",
    Reject: "/message/reject",
    Result: "/message/result",
    PhoneNumber: "/message/auto/input-phoneNumber",
    Preview: "/message/auto/preview",
    Sapm: "/message/declaration/spam",
    GroupCell: "/message/declaration/group-cell",
    RegistrationExel: "/message/reject/exel",
    SMSDetail: "/message/result/detail-content",
  },
  Customer: {
    Registration: "/customer/registration",
  },
  System: {
    Solution: "/system/solution",
    User: "/system/user",
    Member: "/system/member",
    Local: "/system/local",
    LocalMember: "/system/localmember",
    Auth: "/system/auth",
    NetworkSetup: "/system/networksetup",
  },
};

export default PathConstants;
