const PathConstants = {
  Home: "/",
  Login: "/login",
  SiteSelection: "/siteSelection",
  NetworkSetup: "/networkSetup",
  Test: "/test",
  Call: {
    Consultation: "/call/consultation",
    SearchCustomer: "/call/consultation/customer-search",
    ConsultationStatus: "/call/consultation/consultation-status",
    CallLog: "/call/consultation/call-log",
    SmsSending: "/call/consultation/sms-sending",
    RegisterSenderNumber: "/call/consultation/register-sender-number",
    Analysis: "/call/analysis",
    UploadConsultation: "/call/analysis/upload-consultation",
    CreateConsultation: "/call/analysis/create-consultation",
    TopicRegistration: "/call/analysis/topic-registration",
    Management: "/call/management",
    Information: "/call/information",
  },
  Message: {
    Auto: "/message/auto",
    Bulk: "/message/bulk",
    Declaration: "/message/declaration",
    Reject: "/message/reject",
    Result: "/message/result",
    PhoneNumber: "/message/auto/input-phoneNumber",
    Preview: "/message/auto/preview",
    Sapm: "/message/declaration/spam",
    GroupCell: "/message/declaration/group-cell",
    RegistrationExel: "/message/reject/exel",
    SMSDetail: "/message/result/detail-content",
  },
  Customer: {
    Registration: "/customer/registration",
    RegistrationUpload: "/customer/registration/registration-upload",
    CustomerGroupManagement: "/customer/registration/customergroup-management",
  },
  System: {
    Solution: "/system/solution",
    User: "/system/user",
    Member: "/system/member",
    Local: "/system/local",
    LocalMember: "/system/localmember",
    Auth: "/system/auth",
    NetworkSetup: "/system/networksetup",
    UserUpload: "/system/user/uploadUser",
    UpdateUser: "/system/user/updateUser",
    MemberMenuPermission: "/system/auth/memberMenuPermission",
    MenuPermissionCopy: "/system/auth/menuPermissionCopy",
    PermissionRevoke: "/system/auth/permissionRevoke",
    ReceivingNumber: "/system/receivingNumber",
    AuthCode: "/system/authCode",
    Phone: "/system/phone",
    LocalRegistration: "/system/local/localRegistration",
    PhoneAdd: "/system/phone/phoneAdd",
    DeviceType: "/system/phone/deviceType",
  },
  Err: {
    Err404: "/err-not-page-404",
  },
  Notice: {
    NoticeList: "/notice/noticeList",
    NoticeAdd: "/notice/noticeAdd",
    NoticeDetail: "/notice/noticeDetail",
    NoticeModify: "/notice/noticeModify",
  },
  FAQ: {
    FAQList: "/faq/faqList",
    FAQAdd: "/faq/faqAdd",
    FAQDetail: "/faq/faqDetail",
    FAQModify: "/faq/faqModify",
  },
  MyPage: {
    PasswordCheck: "/mypage/passwordCheck",
    UserInfoPopup: "/mypage/userInfo",
    AdminInfoPopup: "/mypage/adminInfo",
  },
};

export default PathConstants;
